# Generated by Django 4.0.3 on 2022-06-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_wizard_type', models.CharField(choices=[('SURVEY_WIZARD_ONE', 'survey_wizard_one'), ('SURVEY_WIZARD_TWO', 'survey_wizard_two'), ('SURVEY_WIZARD_THREE', 'survey_wizard_three'), ('SURVEY_WIZARD_FOUR', 'survey_wizard_four'), ('SURVEY_WIZARD_FIVE', 'survey_wizard_five'), ('SURVEY_WIZARD_SIX', 'survey_wizard_six'), ('SURVEY_WIZARD_SEVEN', 'survey_wizard_seven'), ('SURVEY_WIZARD_EIGHT', 'survey_wizard_eight'), ('SURVEY_WIZARD_NINE', 'survey_wizard_nine')], max_length=1000)),
                ('survey_wizard_count', models.SmallIntegerField(default=0)),
                ('total_max_counter', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('Category', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=10, null=True)),
                ('Production_country', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('Recommended_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
                ('recomended_devices', models.ManyToManyField(related_name='aa', to='home.products')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('OrderItem_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='home.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('category_products', models.ManyToManyField(related_name='categories', to='home.products')),
            ],
        ),
    ]
